
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Example:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make install'
	@echo '	$$ make switch'
	@echo
.PHONY: help




install:
	./install.sh
.PHONY: install




switch:
	./switch.sh
.PHONY: switch
